#!/bin/sh
# blockcontrol - script to manage IP block daemons (MoBlock and NFBlock)
#
# Copyright (C) 2005 - 2009 jre <jre-phoenix@users.sourceforge.net>
# Parts and ideas from JFM, /meth/usr, lestlest (clessing), Morpheus and
# perhaps others. More Info: http://forums.phoenixlabs.org
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

################################################################################
# The following code is common between blockcontrol, blockcontrol.watchdog,
# cron.daily, init and debian/postinst.

# if-up is similar, but exits successfully if CONTROL_MAIN is not there, yet.
# This can happen in early boot stages before local file systems are mounted.

# It sets the variables and loads functions

# CONTROL_MAIN has to be set correctly in all just mentioned files.
CONTROL_MAIN="/usr/lib/blockcontrol/blockcontrol.main"

# Configure blockcontrol and load functions.
if [ -f "$CONTROL_MAIN" ] ; then
	. $CONTROL_MAIN || { echo "$0 Error: Failed to source $CONTROL_MAIN although this file exists."; exit 1; }
else
	echo "$0 Error 7: Missing file $CONTROL_MAIN."
	exit 7
fi

# End of the common code between blockcontrol, blockcontrol.watchdog,
# cron.daily, (if-up), init and debian/postinst.
################################################################################

# And now, make this script usable:
case "$1" in
	'start')
		test_CONTROL_LOG
		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Starting $DESC" "$NAME"
		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		do_start >> $CONTROL_LOG 2>&1
		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
		;;
	'stop')
		test_CONTROL_LOG
		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Stopping $DESC" "$NAME"
		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		do_stop >> $CONTROL_LOG 2>&1
		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
		;;
	'start_watchdog')
		test_CONTROL_LOG
		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Starting $CONTROL_NAME watchdog" "$CONTROL_NAME.watchdog"
		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		do_start_watchdog >> $CONTROL_LOG 2>&1
		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
		echo ""
		;;
	'stop_watchdog')
		test_CONTROL_LOG
		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Stopping $CONTROL_NAME watchdog" "$CONTROL_NAME.watchdog"
		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		do_stop_watchdog >> $CONTROL_LOG 2>&1
		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
		echo ""
		;;
	'restart')
		test_CONTROL_LOG
		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Restarting $DESC" "$NAME"
		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		do_restart >> $CONTROL_LOG 2>&1
		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
		;;
	'reload'|'force-reload')
		test_CONTROL_LOG
		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Reloading $DESC" "$NAME"
		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		do_reload >> $CONTROL_LOG 2>&1
		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
		;;
	'update'|'force-update')
		test_CONTROL_LOG
		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Updating blocklists and reloading $DESC" "$NAME"
		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		if [ "$1" = "force-update" ] ; then
			echo -n "Forcing update of all lists. Removing $BLOCKLISTS_DIR" >> $CONTROL_LOG
			rm -rf $BLOCKLISTS_DIR >> $CONTROL_LOG 2>&1 \
				|| { log_failure_msg " Error: rm exited with $?" >> $CONTROL_LOG ; exit 1; }
			echo "." >> $CONTROL_LOG
		fi
		update_blocklists >> $CONTROL_LOG 2>&1
		do_reload >> $CONTROL_LOG 2>&1
		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
		if [ "$VERBOSITY" -gt 0 ] ; then
			log_end_msg $RETVAL
			IFS=";"
			if [ -n "$UPDATE_FAIL" ] ; then
				echo ""
				echo "The following lists failed to update but have old usable versions:"
				for i in $UPDATE_FAIL ; do
					echo "$i"
				done
			fi
			if [ -n "$UPDATE_SUCCESS" ] ; then
				echo ""
				echo "The following lists were updated:"
				for i in $UPDATE_SUCCESS ; do
					echo "$i"
				done
			fi
			if [ -n "$UPDATE_SUCCESS_NA" ] ; then
				echo ""
				echo "For the following lists there was no update available:"
				for i in $UPDATE_SUCCESS_NA ; do
					echo "$i"
				done
			fi
			if [ -n "$UPDATE_LOCAL" ] ; then
				echo ""
				echo "The following local blocklists are used:"
				for i in $UPDATE_LOCAL ; do
					echo "$i"
				done
			fi
			IFS=$STDIFS
		fi
		;;
	'status')
		echo "Current IPv4 iptables rules (this may take a while):"
		echo
		iptables -L -nv
		if [ "$(lsmod | grep ipv6)" ] ; then
			echo
			echo "Current IPv6 iptables rules (this may take a while):"
			echo
			ip6tables -L -nv
		fi
		echo
		echo "Please check if the above printed iptables rules are correct!"
		echo
		status_of_proc $DAEMON $NAME
		if [ "$?" -eq 0 ] ; then
			echo "PID: $(cat $PIDFILE)    CMD: $(ps -o cmd -p $(cat $PIDFILE) | tail -1)"
			echo
		fi

		status_of_proc $WATCHDOG_PATH $(basename $WATCHDOG_PATH)
		if [ "$?" -eq 0 ] ; then
			echo "PID: $(cat $WDPIDFILE)    CMD: $(ps -o cmd -p $(cat $WDPIDFILE) | tail -1)"
			echo
		fi
		;;
	'stats')
		status_of_proc $DAEMON $NAME > /dev/null 2>&1
		if [ "$?" -eq 0 ] ; then
			echo "Dumping stats..."
			dump_stats
		fi
		;;
	'reset_stats')
		status_of_proc $DAEMON $NAME > /dev/null 2>&1
		if [ "$?" -eq 0 ] ; then
			echo "Dumping stats to $STATFILE..."
			reset_stats
		fi
		;;
	'show_config')
		echo "$(basename $0) current settings:"
		# Read all variables that are defined in CONTROL_DEFAULTS
		VARIABLES="$(grep -Ev "^[[:space:]]*#" $CONTROL_DEFAULTS | grep "=" | sed "s|=.*||" | sort -u)"
		for VAR in $VARIABLES ; do
			eval VALUE=\$$VAR
			# This gives the actually used value of the variable (not necessarily that which is set in CONTROL_DEFAULTS).
			echo ${VAR}=\"$VALUE\"
		done
		echo
		echo "The following blocklists are configured to be used:"
		set_LISTS_URL
		for LIST in $LISTS_URL ; do
			echo "$LIST"
		done
		;;
	'test')
		test_ipblocking
		;;
	'search')
		[ "$#" -eq 2 ] || { echo "Usage: $(basename $0) search SEARCHPATTERN" ; exit $E_BADARGS ; }
		SEARCHPATTERN="$2"
		search
		;;
	*)
		echo "Usage: $(basename $0) OPTION"
		echo "Options:"
		echo "        start"
		echo "        stop"
		echo "        start_watchdog"
		echo "        stop_watchdog"
		echo "        restart"
		echo "        reload"
		echo "        update"
		echo "        force-update"
		echo "        status"
		echo "        test"
		echo "        stats"
		echo "        reset_stats"
		echo "        show_config"
		echo "        search"
		exit $E_BADARGS
		;;
esac
exit $RETVAL
