#!/bin/sh
# if-up - insert blockcontrol iptables whitelisting rules for newly brought up
# interfaces.
# Copyright (C) 2008 - 2009 jre <jre-phoenix@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

################################################################################
# The following code is common between blockcontrol, blockcontrol.wd,
# cron.daily, init and debian/postinst.

# if-up is similar, but exits successfully if CONTROL_MAIN is not there, yet.
# This can happen in early boot stages before local file systems are mounted.

# CONTROL_MAIN has to be set correctly in all just mentioned files.
CONTROL_MAIN="/usr/lib/blockcontrol/blockcontrol.main"

# Configure blockcontrol and load functions.
if [ -f "$CONTROL_MAIN" ] ; then
	. $CONTROL_MAIN || { echo "$0 Error: Failed to source $CONTROL_MAIN although this file exists."; exit 1; }
else
	exit 0
fi

# End of the common code between blockcontrol, blockcontrol.wd,
# cron.daily, (if-up), init and debian/postinst.
################################################################################

test_root
# If the daemon is not running, just exit gracefully:
status_of_proc $DAEMON $NAME > /dev/null 2>&1 || exit 0
test_IPTABLES_VARS
# Exit if user doesn't want automatic whitelisting:
[ "$IPTABLES_SETTINGS" -eq 0 ] && exit 0
[ "$WHITE_LOCAL" -eq 0 ] && exit 0
test_DAEMON
test_CONTROL_SCRIPT
test_external iptables || exit $?

[ "$WHITE_LOCAL" -eq 1 ] && white_lan >> $CONTROL_LOG 2>&1
[ "$WHITE_LOCAL" -ne 0 ] && [ -f /etc/resolv.conf ] && white_dns >> $CONTROL_LOG 2>&1

exit 0
