#!/bin/sh

set -e

if test "$1" = "configure"; then
    ENABLED=0

    test -f /etc/default/pgl && . /etc/default/pgl

    if [ "$ENABLED" = "0" ]; then
        exit 0
    fi

    mkdir -p /var/lib/pgl

fi

#DEBHELPER#

exit 0
